services:
  pr-dashboard:
    image: pr-dashboard:latest
    container_name: pr-dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
